from .administrador import Administrador
from .assinatura import Assinatura
from .cliente import Cliente
from .fatura import Fatura
from .ligacao import Ligacao
from .mensagem import Mensagem
from .numero import Numero
from .plano import Plano
from .solicitacao import Solicitacao
from .usuario import Usuario